export const GET_ORDERS = "GET_ORDERS";
export const ORDERS_FAIL = "ORDERS_FAIL";
export const ORDER_STATE_UPDATE = "ORDER_STATE_UPDATE";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const ORDER_REVIEW = "ORDER_REVIEW";
export const GET_REVIEWS = "GET_REVIEWS";