export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";
export const CREATE_CLOTHE = "CREATE_CLOTHE";
export const EDIT_CLOTHE = "EDIT_CLOTHE"

export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

export const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";

export const USER_INFO_FAIL = "USER_INFO_FAIL";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";

